apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: docker.io/bitnami/grafana:9.2.2
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-builtin-admin
                  key: password
          volumeMounts:
            - name: emotion
              mountPath: /opt/bitnami/grafana/data/custom_dashboards/emotion.json
              subPath: emotion.json
            - name: asm-terni
              mountPath: /opt/bitnami/grafana/data/custom_dashboards/asm_terni.json
              subPath: asm_terni.json
            - name: grafana-dashboards
              mountPath: /opt/bitnami/grafana/conf/provisioning/dashboards/all.yaml
              subPath: all.yaml
            - name: grafana-datasources
              mountPath: /opt/bitnami/grafana/conf/provisioning/datasources/all.yaml
              subPath: all.yaml
      volumes:
        - name: emotion
          configMap:
            name: grafana-emotion-dashboard
        - name: asm-terni
          configMap:
            name: grafana-asm-terni-dashboard
        - name: grafana-dashboards
          configMap:
            name: grafana-dashboards
        - name: grafana-datasources
          configMap:
            name: grafana-datasources